services:
  postgres:
    image: postgres:16.0
    container_name: banking-postgres
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank"]
      interval: 5s
      timeout: 5s
      retries: 10

  personas-clientes:
    build:
      context: ../personas-clientes
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres:5432/personasdb
      DB_USER: bank
      DB_PASS: bank
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["8081:8080"]

  cuentas-movimientos:
    build:
      context: ../cuentas-movimientos
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres:5432/cuentasdb
      DB_USER: bank
      DB_PASS: bank
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["8082:8080"]

volumes:
  pgdata:
